"""Generate an entirely synthetic populated schema fixture (no reference values)."""
import base64
import io
import json
from pathlib import Path
import h5py
import numpy as np

buffer = io.BytesIO()
with h5py.File(buffer, 'w') as f:
    def group(path, **attrs):
        g = f.require_group(path)
        for k, v in attrs.items():
            g.attrs[k] = v
        return g

    def dataset(g, name, values):
        a = np.asarray(values)
        if a.dtype.kind in 'OU':
            g.create_dataset(name, data=a.astype(object), dtype=h5py.string_dtype('utf-8'))
        else:
            g.create_dataset(name, data=a, compression='gzip')

    group('MetaData', Project='Synthetic', BodyMass='unknown')
    group('MetaData/Location', Lat='unknown', Lon='unknown')
    dataset(f['MetaData'], 'Calibration', np.array([3, 4], dtype=np.int16))
    group('CustomFields', Opaque='preserve me')
    group('Trajectories', NumFrames=8, StartFrame=8, EndFrame=15, SamplingFrequency=4.)
    g = group('Trajectories/Labeled', Labels=['A', 'B'], Unit='mm', NumLabeled=2,
              ResidualStatus='NaN means unavailable; negative means invalid')
    dataset(g, 'Data', np.arange(64, dtype=np.float64).reshape(2, 4, 8) + .123456789)
    residuals = np.zeros((2, 8)); residuals[0, 1] = np.nan; residuals[1, 2] = -1
    dataset(g, 'Residuals', residuals)
    dataset(g, 'Time', 2 + np.arange(8) / 4)
    dataset(g, 'Type', np.ones((2, 8), dtype=np.int8))
    dataset(g, 'CameraMasks', (np.arange(48).reshape(2, 3, 8) % 2).astype(bool))
    dataset(g, 'CameraMasksKnown', np.array([True, False]))
    dataset(g, 'Virtual', np.array([False, True]))
    for name in ['Analog', 'EMG']:
        g = group(name, Labels=['Channel'], Channels=np.array([0], dtype=np.int64),
                  Units=['V'], SamplingFrequency=8., NumSamples=16)
        dataset(g, 'Data', np.arange(16, dtype=np.float64).reshape(1, 16))
        dataset(g, 'Time', 2 + np.arange(16) / 8)
    g = group('ForcePlates/0', Name='Plate', SchemaVersion=2, CoordinateSystem=1,
              FreeMomentFrame='global', NumSamples=16, SamplingFrequency=8.,
              unit_force='N', unit_moment='Nmm', unit_position='mm')
    for name in ['Force', 'Moment', 'COP', 'Tz', 'Position']:
        dataset(g, name, np.arange(48, dtype=np.float64).reshape(3, 16) + .25)
    dataset(g, 'Corners', np.arange(192, dtype=np.float64).reshape(3, 4, 16))
    dataset(g, 'Rotation', np.repeat(np.eye(3)[:, :, None], 16, axis=2))
    dataset(g, 'Origin', np.array([[0.], [0.], [-50.]]))
    dataset(g, 'Time', 2 + np.arange(16) / 8)
    group('RigidBodies', SchemaVersion=1)
    g = group('RigidBodies/0', Name='Body', NumSamples=8, Unit='mm')
    dataset(g, 'Position', np.arange(24, dtype=np.float64).reshape(3, 8))
    dataset(g, 'Rotation', np.repeat(np.eye(3)[:, :, None], 8, axis=2))
    dataset(g, 'Markers', ['A', 'B'])
    for name in ['IKResults', 'IDResults']:
        g = group(name, Labels=['time', 'quantity'], Metadata='{}', NumSamples=4)
        times = np.array([1.75, 2.3, 3.6, 4.5])
        dataset(g, 'Data', np.array([times, [4., 5., 6., 7.]]))
        dataset(g, 'Time', times)
    g = group('Events', SchemaVersion=1, Scope='Trial clock; zero-based source point frames; seconds')
    dataset(g, 'Name', ['Late', 'Early', 'Outside'])
    dataset(g, 'Description', ['Unicode: Fuß', ' keep spaces ', ''])
    dataset(g, 'Frame', np.array([13, 9, 20], dtype=np.int64))
    dataset(g, 'Time', np.array([3.25, 2.25, 5.]))

root = Path(__file__).resolve().parents[1]
(root / 'tests/fixtures/institute-h5.json').write_text(json.dumps({
    'description': 'Entirely synthetic; generated by scripts/create-h5-fixture.py',
    'base64': base64.b64encode(buffer.getvalue()).decode('ascii'),
}) + '\n', encoding='utf-8')
