"""Generate only the current institute H5 synthetic fixture; no reference values."""
import base64
import io
import json
from pathlib import Path

import h5py
import numpy as np

buffer = io.BytesIO()
with h5py.File(buffer, 'w') as f:
    def group(path, **attrs):
        g = f.require_group(path)
        for key, value in attrs.items():
            g.attrs[key] = value
        return g

    def dataset(g, name, values):
        values = np.asarray(values)
        if values.dtype.kind in 'OU':
            g.create_dataset(name, data=values.astype(object), dtype=h5py.string_dtype('utf-8'))
        else:
            g.create_dataset(name, data=values, compression='gzip')

    group('MetaData/Project', SubjectID='SYNTHETIC', SubjectGroup='Control', Age='30',
          BodyHeight='175', BodyMass='70', Sex='unknown', Condition='Baseline',
          Project='Synthetic', ProjectPI='Example')
    group('MetaData/FileInfo', FileCreationLocal='2026-01-01T12:00:00',
          FileCreationUTC='2026-01-01T11:00:00Z', LastUpdate='2026-01-02',
          OriginalFiles=['synthetic.c3d'], PathFile='synthetic.c3d')
    group('MetaData/Location', Lat='unknown', Lon='unknown')
    dataset(f['MetaData'], 'Calibration', np.array([3, 4], dtype=np.int16))
    for name, labels in [('POINT', ['A', 'B']), ('ANALOG', ['Channel'])]:
        g = group(f'MetaData/C3DParameters/{name}/LABELS')
        for key, value in dict(value=labels, type=-1, description='Synthetic parameter', is_locked=False).items():
            g.attrs[key] = value
        group(f'MetaData/C3DParameters/{name}/__METADATA__',
              IS_LOCKED=True, DESCRIPTION='Synthetic group')
    f['MetaData/C3DParameters'].attrs['SyntheticFlags'] = np.array([True, False])
    group('CustomFields', Opaque='preserve me')
    group('Trajectories', NumFrames=8, StartFrame=8, EndFrame=15, SamplingFrequency=4.)
    g = group('Trajectories/Labeled', Labels=['A', 'B'], Unit='mm', NumLabeled=2,
              ResidualStatus='NaN means unavailable; negative means invalid')
    dataset(g, 'Data', np.arange(64, dtype=np.float64).reshape(2, 4, 8) + .123456789)
    residuals = np.zeros((2, 8))
    residuals[0, 1] = np.nan
    residuals[1, 2] = -1
    dataset(g, 'Residuals', residuals)
    dataset(g, 'Time', 2 + np.arange(8) / 4)
    dataset(g, 'Type', np.ones((2, 8), dtype=np.int8))
    dataset(g, 'Virtual', np.array([False, True]))
    for name in ['Analog', 'EMG']:
        g = group(name, Labels=['Channel'], Channels=np.array([0], dtype=np.int64),
                  Units=['V'], SamplingFrequency=8., NumSamples=16, StartFrame=16, EndFrame=31)
        dataset(g, 'Data', np.arange(16, dtype=np.float64).reshape(1, 16))
        dataset(g, 'Time', 2 + np.arange(16) / 8)
    g = group('ForcePlates/0', Name='Plate', CoordinateSystem=1,
              FreeMomentFrame='global', NumSamples=16, SamplingFrequency=8.,
              StartFrame=16, EndFrame=31, FrameStep=1,
              unit_force='N', unit_moment='Nmm', unit_position='mm')
    for name in ['Force', 'Moment', 'COP', 'Tz', 'Position']:
        dataset(g, name, np.arange(48, dtype=np.float64).reshape(3, 16) + .25)
    dataset(g, 'Corners', np.arange(192, dtype=np.float64).reshape(3, 4, 16))
    dataset(g, 'Rotation', np.repeat(np.eye(3)[:, :, None], 16, axis=2))
    dataset(g, 'Origin', np.array([[0.], [0.], [-50.]]))
    dataset(g, 'Time', 2 + np.arange(16) / 8)
    g = group('RigidBodies/0', Name='Body', NumSamples=8, Unit='mm', StartFrame=0, EndFrame=7)
    dataset(g, 'Position', np.arange(24, dtype=np.float64).reshape(3, 8))
    dataset(g, 'Rotation', np.repeat(np.eye(3)[:, :, None], 8, axis=2))
    dataset(g, 'Markers', ['A', 'B'])
    for name in ['IKResults', 'IDResults']:
        g = group(name, Labels=['time', 'quantity'], Metadata='{}', NumSamples=4)
        times = np.array([0., .2, .5, .75])
        dataset(g, 'Data', np.array([times, [4., 5., 6., 7.]]))
        dataset(g, 'Time', times)
    f['IKResults'].attrs['Metadata'] = "{'version': '1', 'nRows': '4', 'nColumns': '2', 'inDegrees': 'yes'}"
    g = group('Events')
    for name, values in dict(Name=['Late', 'Early', 'Outside'],
                             Description=['Unicode: Fuß', ' keep spaces ', ''],
                             Context=['Left', 'Right', 'General'],
                             Subject=['', 'Synthetic', '']).items():
        dataset(g, name, values)
    dataset(g, 'Frame', np.array([13, 9, 20], dtype=np.int64))
    dataset(g, 'Time', np.array([3.25, 2.25, 5.]))
    dataset(g, 'GenericFlag', np.array([0, 1, 0], dtype=np.int64))
    dataset(g, 'IconID', np.array([2, 3, 4], dtype=np.int64))

root = Path(__file__).resolve().parents[1]
(root / 'tests/fixtures/current-h5.json').write_text(json.dumps({
    'description': 'Entirely synthetic; generated by scripts/create-h5-fixture.py',
    'base64': base64.b64encode(buffer.getvalue()).decode('ascii'),
}) + '\n', encoding='utf-8')
